version: "3.8"
services:
  ng:
    build: .
    entrypoint: "ng serve --host 0.0.0.0"
    volumes: 
      - ./:/frontend/
      - /frontend/node_modules # to avoid copy node_mudules again.
    ports:  
      - "4200:4200"
    stdin_open: true
    tty: true