version: "3.8"
services:
  ng:
    build: .
    ports:
      - "4200"
    entrypoint: "ng serve --host 0.0.0.0"
    volumes: 
      - ./:/frontend/
     # - /frontend/node_modules # if you choose avoid node_modules, use this volume as well
    ports:  
      - "4200:4200"
    stdin_open: true
    tty: true